"""
Game constants and configuration values.
"""

# Canvas dimensions
CANVAS_WIDTH = 360
CANVAS_HEIGHT = 390

# Grid dimensions
CELL_SIZE = 96
GRID_WIDTH = 3 * CELL_SIZE
GRID_HEIGHT = 3 * CELL_SIZE

# Grid positioning
GRID_OFFSET_Y = 80  # Space for title
TITLE_Y = 40

# Mark dimensions
MARK_SIZE = 30
MARK_LINE_WIDTH = 6

# Animation settings
ANIMATION_STEPS_X = 15
ANIMATION_STEPS_O = 30
ANIMATION_DELAY_X = 20
ANIMATION_DELAY_O = 15
ANIMATION_DELAY_WINNING_LINE = 30
ANIMATION_STEPS_WINNING_LINE = 20
BOUNCE_STEPS = 20
BOUNCE_DELAY = 30
FADE_STEPS = 10
FADE_DELAY = 20

# Colors
COLOR_BACKGROUND = "#F5F1E8"
COLOR_CANVAS_BG = "#FFF9E8"
COLOR_GRID_LINE = "#34495E"
COLOR_TITLE = "#2C3E50"
COLOR_X_MARK = "#E74C3C"
COLOR_O_MARK = "#3498DB"
COLOR_WINNING_LINE = "#F39C12"
COLOR_DRAW = "#95A5A6"
COLOR_BUTTON_BG = "#2ECC71"
COLOR_BUTTON_HOVER = "#27AE60"
COLOR_BUTTON_OUTLINE = "#27AE60"
COLOR_BUTTON_TEXT = "white"

# Grid line settings
GRID_LINE_WIDTH = 4

# Winning line padding
WINNING_LINE_PADDING = 10
WINNING_LINE_CORNER_PADDING = 20

# Button dimensions
BUTTON_WIDTH = 110
BUTTON_HEIGHT = 35
BUTTON_Y = 230

# Font settings
FONT_FAMILY_PRIMARY = "Comic Sans MS"
FONT_FAMILY_FALLBACK = "Arial"
TITLE_FONT_SIZE = 32
RESULT_FONT_SIZE = 22
BUTTON_FONT_SIZE = 12
